export type ResourceItem = { label: string; detail: string; url: string };
export type ResourceGroup = { label: string; icon: string; description: string; links: ResourceItem[] };
export type Subject = { id: string; code: string; name: string; description: string; icon: string; color: string; folderUrl: string; advice: { summary: string; points: string[]; sourceUrl: string }; groups: ResourceGroup[] };

const file = (label: string, detail: string, id: string): ResourceItem => ({ label, detail, url: `https://drive.google.com/file/d/${id}/view?usp=drivesdk` });
const folder = (label: string, detail: string, id: string): ResourceItem => ({ label, detail, url: `https://drive.google.com/drive/folders/${id}` });

export const driveRoot = 'https://drive.google.com/drive/folders/1YPJz4-7eti_-8uZo7OwZdIvmXqqau3qu';

const circuitWeeks = [
  ['Week 1', '14eaf6ImuQCDMfqY4lIsuRdF5WL96rQyq'], ['Week 2', '1PX_Fs4y0F8FRi84HWPmxTmtiLv49p8f2'], ['Week 3', '1qWSWseyXJc4MAh833atog3GQ1VMwXmJ8'], ['Week 4', '1tjRvyl9T4zCZXtIPN1Px-5mhdXu3WOMb'], ['Week 5', '1QgLUquTW65tXTpbue2Z1vMt0JBKQWK1G'], ['Week 6', '1lEd-zkv09i9wpzeKWZlNZLHCfigzwdSL'], ['Week 7', '1db8OlIHsXpkRtZbIdIFVBkOG8hrk_hNh'], ['Week 8', '1zXXsGWdpa18e3em3ZHrQCgqofJkrzwl6'], ['Week 9', '1SD6R5V3IdbCB-K1x-wwlWJHQZHBQAlu0'], ['Week 10', '1TYkkjPpvDDPbBBa7Vti-kAzFKbftNTUg'], ['Week 11', '1rTuYqYnX1AStuDno4nzb8rMV7u5pJgxI'], ['Week 12', '1gGBaBB_-5w3lyLzFkUmCdq6A1I9-YSSW'], ['Week 13', '1KznvmaPDgw8QHgbjDzxEqIrFOkbUKfH7'], ['Week 14', '1D0DvFriGSHKvK2wCTObPwnWeNFBqL0Ir'],
].map(([label, id]) => file(label, 'Lecture note', id));

const digitalWeeks = [
  ['W1 Number Systems.pdf', '1VkNF_kvoznRiiBHavUAX_79Og5RcdcCA'],
  ['W2 KIE1003 Binary Arithmetic Operations and Coding Systems.pdf', '1C7_S3RWXTqz3Y5jM8JzODn1FGNF2yEWF'],
  ['W2 Logic Gates - Boolean Algebra.pdf', '1S0jZuGdsMy48ClXGJYqC0PtjS5-4iceh'],
  ['W3 Logic Gates - Boolean Algebra.pdf', '1S5j_qblLwGi3AlTGR-krvaIk-BYKdjuB'],
  ['W3 Circuit Optimization - Karnaugh Map.pdf', '1CMCllisUodhl3vG2QcMIogaAyKeJUZnv'],
  ['W4 Circuit Optimization - Karnaugh Map.pdf', '1GkAEtT9qaXYW8Nfm8-dFukxcfs0d3R5g'],
  ['W5 Combinational Logic.pdf', '1J0yPcYny2WSQpCIJy9sh62M6l0rGyIE_'],
  ['W6 Decoder - Encoder.pdf', '1PSUqR19y-eFjqrBAWsiqXvS6NrrEQ-sN'],
  ['W6 KIE1003 Decoder and Encoder.pdf', '1sw5Hn5K6fLVGj1il28eHZm6IsW2O4Q6N'],
  ['W7 KIE1003 Applications of Decoder and Encoder.pdf', '1hq-YbFCm_y-Wcx3wBtJ7VWzM-GwAATfB'],
  ['W8_9 Mux and Demux.pdf', '1mOw0lA4YP1AZjsNxwqxApqF57tye3pv5'],
  ['W10_11 Adders_Substractors_Arithmetic.pdf', '1BF9e3AV9Kfu4d-MvBayyiNGVDgxLIUuy'],
  ['W12 Sequential Circuits_Latches and Flip flops.pdf', '1gD_zBrOWaSU_f4CjKnWYa6Rlnd48Q673'],
  ['W13 State Table  Diagram, Timing Diagrams and.pdf', '1MNralpTiLFTXHhzxQzsCBUoyP6jv5mSJ'],
  ['W14_Finite State Machine.pdf', '1OxPkgosZUWN9IetMlVCNZ_VHrTQjsHDu'],
].map(([label, id]) => file(label, 'Lecture note', id));

const programmingWeeks = [
  ['W1 Intro to Computer.pdf', '1C6QDF0JYf3vQAfKqspydUpAbjFhnV_q9'],
  ['W2 Basic Concepts 1.pdf', '1pIBJL-NMyalqsYoLriUE6hEVs0q7U_Ad'],
  ['W3_Basic Concepts 2.pdf', '1YyST-uMRtXFtY_vPpYYldC0GWokHia_B'],
  ['W4 Control Statements 1.pdf', '1Gn9QwZXcrv3hSt60mHea2Fv8RRq8S_fW'],
  ['W5_Control Statements 2.pdf', '1Ts5hz1shgWf3KKJcDG-eRfub6yJt1yt7'],
  ['W6_Problem Solving.pdf', '1jEQbStLPSrn7TJT1BgeYYqetnu_TSSyQ'],
  ['W7_Functions 1.pdf', '1csuDLVzRrFNVXOIvzr_aDZFrlKqvuwUV'],
  ['W8_Functions 2.pdf', '12dlovPiyQkboao0tvlJGG7yCKpAujwFP'],
  ['W9_Arrays.pdf', '1wSz8cUwvlNfjXemMhyLYaNI8pTtEKZDQ'],
  ['W10_Multidimensional Arrays.pdf', '1Qpa1d0QRLUCmxw3lA9rGSQKjLWtkRUpd'],
  ['W11_Searching and Sorting.pdf', '1edDSfjDUWZF_wJPIOPiDX84LnnaRUodh'],
  ['W12_Pointers- Declaration and Initialization.pdf', '1UWdf8ZpajZquwvaf49SHGU7iFRK9vfI6'],
  ['W13_Pointers- Pass by Reference.pdf', '1XVZKRYZSR1IJaKQzhSIpq5rAYSg9l6uB'],
].map(([label, id]) => file(label, 'Lecture note', id));

const mathWeeks = [
  file('Week 1 Notes.pdf', 'Lecture note', '12oJ2m3VOtEDwa4soPUN-R7yPD1tif7wV'),
  file('Week 1 Lecture.pdf', 'Lecture note', '1hxtx-hxiqe38nDrp75X2oDQiVzjJofmj'),
  file('Week 2 Notes.pdf', 'Lecture note', '1WeFKbZAX8bPuD55NJvbPNCb8Mm2pRu_4'),
  file('Week 2 Lecture.pdf', 'Lecture note', '1GlJO9rt82lxYPfUePMGhHaiMQeeKkCtn'),
  file('Week 3 - 5 Notes.pdf', 'Lecture note', '1jHgrsfWcINDEqajhuBDQWZzuQJzanuCx'),
  file('Week 6 - 7 Notes.pdf', 'Lecture note', '1CMnvPVmk4HF8NN8D8tHQCf5ZHSTCLVYB'),
  file('Week 8_Integration.pdf', 'Lecture note', '11zmsZnDkQoL_8OeBf6HQgdbfDLyVKjqS'),
  file('Week 8 - 9 Notes.pdf', 'Lecture note', '1rUNDWsg9d9OD1hxod6cSQ60-Hx3E-FTm'),
  file('Week 9_Engineering Application Of Integrals.pdf', 'Lecture note', '1FYNu7u9B4iMbX0ymXHrkJsw6ULUR8GaG'),
  file('Week 10_Multiple Integrals.pdf', 'Lecture note', '1kh7SqRSEckYTkRP1OB6FHRIlxK1bSyyd'),
  file('Week 11_Multiple Integrals In Polar Coordinate.pdf', 'Lecture note', '1f3ykbB9fPD_tn_4rFzGoGxfBaN2V5yse'),
  file('Week 12_Line Integrals.pdf', 'Lecture note', '1qYu9GH5WMu4wSXJsJPOtc9IUEpHRi7hT'),
  file('W13_Surface Integrals.pdf', 'Lecture note', '1NHBqc3DYGMSAYXoZiktmhFe3QsNpMt_O'),
  file('W14_Stokes Theorem.pdf', 'Lecture note', '1QhYQOiUyRqC37zK-b0r7LHfbdWzFfEwi'),
];

export const subjects: Subject[] = [
  {
    id: 'circuit-analysis', code: 'KIE1005', name: 'Circuit Analysis', icon: '∿', color: 'purple', description: 'Circuit laws, methods, worked examples, and exam practice.', folderUrl: 'https://drive.google.com/drive/folders/1OTO3rkn7jFDCeID5v0CluyBH7bDxt9dD', advice: { summary: 'Make this your highest-priority course: build a weekly practice habit instead of leaving it for exam week.', sourceUrl: 'https://docs.google.com/document/d/1OpJF5JHgP7Ivi7thu0RthkGohIeYLDmwlQKF_qzwplg/edit?usp=drivesdk', points: ['If a slide is unclear, switch to the textbook, a worked video, or a classmate’s explanation. Use AI only to clarify and then verify it against your notes.', 'Do textbook end-of-chapter questions and assessment problems yourself. Reading a solution is not the same as being able to reproduce the method.', 'Practise circuit setup, equations, units, and signs. In an exam, show your working because method marks may depend on it.', 'Keep up every week. The volume of methods and exercises makes last-minute study especially frustrating.'] }, groups: [
      { label: 'Lecture notes', icon: '▤', description: 'Open lecture notes by week.', links: circuitWeeks },
      { label: 'Past year papers', icon: '▥', description: 'Exam papers and practice archives.', links: [file('Final 23/24', 'Past year paper', '10gapD1QbF5Z84NoiEmwYND_yGuiQQkr2'), file('Mid Test 23/24', 'Past year paper', '1vBAg01A-cSdLY0miwo91U7TUUUFhsgDA'), file('KIE1005 · 2018', 'Past year paper', '10TvuV7RiR6GCeEAytgFQBMM1pru_l1Rc'), file('KIE1005 · 2019', 'Past year paper', '1Cg1zVphA1gDjfiUOX2hFGcbIKrpk7Wb0'), folder('Full past year archive', '25 papers + solutions', '1QxLTfLcPP0zz7wvpofSg_84SOmNN5-EB')] },
      { label: 'Tutorial + solutions', icon: '✎', description: 'Practice papers and worked answers.', links: [file('Test 2024/25', 'Practice paper', '100xsMFj9mZ52w9qMI7o0tLD5q9FM6-25'), file('Test answer', 'Worked answer', '1-zwXq3iqStJf5fvo4GrlnzkwLqc1rLGi'), folder('Textbook with solutions', 'Reference practice', '1hcrXlZjUmzTjobA_tiR5nyqUPvCr6EMh'), folder('Compiled tutorial folder', 'Extra tutorials from your folder', '1pHgF6IgkuzPGOkidO12i8qkbJ5SBQSaE'), file('Tutorial Weeks 1–2 + answers', 'Compiled practice', '1-FeaeKOYpbUThZneAj1d9rCq2iP4zcAw'), file('Tutorial Weeks 3–4 + answers', 'Compiled practice', '1dPM5TgcwfBFxYtW-XA_bKm7_P6zX20zy'), file('Tutorial · Mesh Analysis', 'Compiled practice', '1la392qdY8GjrwtOzJJj6BPy9sdUJEo1h'), file('Tutorial · Node Voltage', 'Compiled practice', '1ZgkAmNTYuRy9CoPRfDVbCzH6vySg8Ian')] },
      { label: 'Additional materials', icon: '+', description: 'Open the complete Circuit Analysis Drive and extra textbooks.', links: [folder('Whole subject Drive', 'All source materials', '1OTO3rkn7jFDCeID5v0CluyBH7bDxt9dD'), file('KIE1005 · 2024 paper', 'Compiled exam paper', '1wI8tDzCLQxE5vyH2uHHMr2pPU2on0eWq'), file('Textbook · Electric Circuits 12th Ed', 'Reference textbook', '1mzByLSYWM3kq9MhyxGvLHyimKfKnOIEc'), file('Textbook solutions · 12th Ed', 'Worked reference', '10JJFmjTmprHEucCpgEwsLazKGWJeS8kn'), file('Circuit Analysis Textbook · 10th Ed', 'Reference textbook', '1svpRpeHUw7l24Rbkxs1Ofs0IGVWuKHq_')] },
    ]
  },
  {
    id: 'engineering-mathematics', code: 'MATHS 1', name: 'Engineering Mathematics 1', icon: '∫', color: 'lavender', description: 'Tutorial questions, solutions, cheat sheets, and past papers.', folderUrl: 'https://drive.google.com/drive/folders/1jHdl6mrcoqJZkJ-Xj0naVGfGijNeYHNs', advice: { summary: 'Prioritize problem-solving method over perfect theory recall, then build your own step-by-step cheat sheet.', sourceUrl: 'https://docs.google.com/document/d/1hGncDsmzU-g03D6XOJw_cYMuF_p3oCemZOUcUim4BT4/edit?usp=drivesdk', points: ['Weeks 1–5 are a gentler start. Give extra practice time to integration, vector analysis, and the later weeks because the question types become more demanding.', 'Master each tutorial without looking at the answer first. Use the solution scheme as a hint, then redo the question independently before the final.', 'Learn the repeatable steps for each question type. Write full working because the final answer alone is only part of the marks.', 'Make a personal formula and method sheet. Check final and midsem coverage with your lecturer because topics can change.'] }, groups: [
      { label: 'Lecture notes', icon: '▤', description: 'Open lecture notes by week.', links: mathWeeks },
      { label: 'Past year papers', icon: '▥', description: 'Questions and solution folders.', links: [folder('Past year questions', 'Question archive', '1XHBvpLQmZ6IdRmJ3ODzVv53kj6oYydrq'), folder('Past year solutions', 'Solution archive', '1reHV0-1fPJJ7FsJiFU_EVZrM135KzKjg')] },
      { label: 'Tutorial + solutions', icon: '✎', description: 'Tutorial questions, solutions, and quick revision.', links: [folder('Tutorial questions', 'Questions archive', '1-Apy7QRVXDeqpY_qqhw_1zCTjHBHxwrm'), folder('Tutorial solutions', 'Solution archive', '1n5Kr5pDPyKL90dqDDe_e8ZJDduryOkGV'), file('Finals cheat sheet', 'Quick revision', '1UFUVg9hPwtrZ-z2jAQ3VTZFc5bB2Dy0i')] },
      { label: 'Additional materials', icon: '+', description: 'Open the complete Engineering Mathematics Drive and your compiled extras.', links: [folder('Whole subject Drive', 'All source materials', '1jHdl6mrcoqJZkJ-Xj0naVGfGijNeYHNs'), folder('Compiled tutorial folder', 'Extra tutorials from your folder', '1WvRfZL1vHEjyzeQPtKyOvO5B-O1x9uIf'), file('KIX1001 · 2024 paper', 'Compiled exam paper', '1MbvKSR2Gkcd9MQWE4J7fPVzuyalOcJUV'), file('Exercises · Weeks 1–2', 'Compiled practice', '1qSkWPYOrOFXvmRxnModfjKb_lfD5CUHL'), file('KIX1001 · 23–24', 'Compiled exam paper', '1eP1CqeM9gbJ_-Swc_2cMvnsXogIjACc5')] },
    ]
  },
  {
    id: 'digital-system', code: 'KIE1003', name: 'Digital System', icon: '01', color: 'blue', description: 'Tutorials, assignments, tests, notes, and past papers for digital logic.', folderUrl: 'https://drive.google.com/drive/u/0/folders/1oWv1BmxjrM9BKAx7pve8h9wTIbAbOT0r', advice: { summary: 'Build the fundamentals early: Digital System repeats the same logic in different forms.', sourceUrl: 'https://docs.google.com/document/d/1eqbmDeWmemdkKpIZaoDyd2Xct4fqhKKMcOrkVbJUDPk/edit?usp=drivesdk', points: ['Master number systems, Boolean algebra, K-maps, and circuit drawing first. They support many later topics.', 'Be able to differentiate and draw mux, demux, decoder, encoder, latches, and flip-flops—not just recognize their names.', 'Do the current tutorials carefully. Older past papers may follow a different syllabus, so use them for practice rather than assuming every question will repeat.', 'If a concept is unclear, use the compiled resources or a reliable lecture recording, then return to the tutorial and solve without help.'] }, groups: [
      { label: 'Lecture notes', icon: '▤', description: 'Open lecture notes by week.', links: digitalWeeks },
      { label: 'Past year papers', icon: '▥', description: 'Exam folders by academic year plus compiled midsem tests.', links: [folder('23/24', 'Past year folder', '1OFDkjd83sURdAnb3zgcCpzMNKsIeeukx'), folder('22/23', 'Past year folder', '1y0ruYu-TpgnYM8Q_Bm4mufIykY0HV7xf'), folder('20/21', 'Past year folder', '1TZWXmtlBQZY5JypseQovPA3imOHESEwG'), folder('19/20', 'Past year folder', '18oMIlbi00cWa0AmkI6DSvYh50b1_PpHu'), folder('Full past year archive', '11 exam folders', '1cR129v2NfgIEOnAoanTWMEuUL0_SZO_h'), folder('Compiled midsem test folder', 'Extra tests from your folder', '15cWuJS5qnUmBJNepPbpqllLVb5uymfl6')] },
      { label: 'Tutorial + solutions', icon: '✎', description: 'Weekly tutorial files and supporting work.', links: [file('Tutorial 1', 'Practice tutorial', '1Uq9LBa4tEPxFv7IdtYqa_-qmTuJQKQ56'), file('Tutorial 5 · solution', 'Worked solution', '1vvXmqAY2X1BOc41SAzACurOUrjQoQrsj'), file('Tutorial 7 · solution', 'Worked solution', '1tHQFR3owMrWf0Y2pShyo056ISF4u7fkA'), folder('Full tutorial archive', '24 files', '1KYYwSbTI8mRpHkVxutFvF4-82nBdDtHt'), folder('Compiled tutorial folder', 'Extra tutorials from your folder', '1wJ1IZBVPamZWYih8rzJGKKXSI4sUERwf')] },
      { label: 'Additional materials', icon: '+', description: 'Open the complete Digital System Drive and compiled resources.', links: [folder('Whole subject Drive', 'All source materials', '1oWv1BmxjrM9BKAx7pve8h9wTIbAbOT0r')] },
    ]
  },
  {
    id: 'programming', code: 'KIE1004', name: 'Programming I', icon: '</>', color: 'indigo', description: 'Weekly tutorials, assignments, reference books, and practice exams.', folderUrl: 'https://drive.google.com/drive/u/0/folders/1FPcj7a-Zqta31Z4DiyTvOdgylMvi6dqM', advice: { summary: 'Keep this course steady and practical: the goal is to build a “compiler in your head” by writing code yourself.', sourceUrl: 'https://docs.google.com/document/d/1yVbNWalJaUaSL2AycGjeHpqULkATKOeEzazLaAnsaCA/edit?usp=drivesdk', points: ['Understand program flow, conditions, functions, arrays, searching, sorting, and pointers instead of memorizing isolated code.', 'Write every tutorial question from scratch, run it, and debug it line by line. This is more useful than watching someone else code.', 'Use AI as a hint or debugging partner, not as a replacement for your own attempt—especially for assignments and exam preparation.', 'Keep up with lessons without over-stressing. Once the fundamentals are strong, use the remaining time on your harder subjects.'] }, groups: [
      { label: 'Lecture notes', icon: '▤', description: 'Open lecture notes by week.', links: programmingWeeks },
      { label: 'Past year papers', icon: '▥', description: 'Tests, finals, and answer files.', links: [file('KIE1004 · 2020', 'Past year paper', '1d_QeM5xpI0DrRZE1JRSl48nf3nFi28Pn'), file('KIE1004 · Feb 2023', 'Past year paper', '1E6-C3rEPp1ZYhECoNPFXrDap4lvBcMwY'), file('KIE1004 · 2017', 'Past year paper', '1SQ4Cvg-fMVjOMhMb8Lt7KdO4nQ-UC3NL'), file('KIE1004 · Final 2021', 'Past year paper', '1pqOLxLzN85-auV2H7MNz01sLPAw2tPo'), folder('Full past year archive', '9 files', '1j0skbz1AWb8H5A0CmAXNYsDwtTQDWpBP')] },
      { label: 'Tutorial + solutions', icon: '✎', description: 'Weekly practice and assignment support.', links: [file('Tutorial Week 2', 'Practice tutorial', '1pWF403_5gf_tkM904-CaoQVsDOTYFGww'), file('Tutorial Week 8', 'Practice tutorial', '1npi2_fCItp3erBONp2H5fyJlsZvjNKQb'), folder('Group + individual assignments', 'Assignment archive', '1aNSvJJe4RGyAsU57gm6ZqVFqxxRj1E9i'), folder('Full tutorial archive', '11 files', '19J2-peZxWvGpLtf0ighcc8IYkONtm6Wq'), file('Tutorial Week 3', 'Compiled practice', '1OpVx_T3u_GLd_q6DYURgxtAZKvsQiRUZ'), file('Tutorial Week 4', 'Compiled practice', '1ySulETq0BpcDmDVwPld1Ed9nubOxqQPu'), file('Tutorial Week 5', 'Compiled practice', '1WsdWq61OR7TdX7dhZ4ZIS7YQCGfBnpr4'), file('Tutorial Week 7', 'Compiled practice', '1xIl0cSQIb_US-NvLpwbkOqjoUhKnlyKC'), file('Tutorial Week 9', 'Compiled practice', '1WjDUJtc2iLGratzMpys5J5QZcXhEqqC4'), file('Tutorial Week 10', 'Compiled practice', '1TXifNOuDd_ZxkxjWZJ_nWduSPwFZyC5E'), file('Tutorial Week 12', 'Compiled practice', '10XKek9-r-CPqWLw3b3Qn5eJPD5EOFm0c')] },
      { label: 'Additional materials', icon: '+', description: 'Open the complete Programming I Drive and compiled resources.', links: [folder('Whole subject Drive', 'All source materials', '1FPcj7a-Zqta31Z4DiyTvOdgylMvi6dqM')] },
    ]
  },
];

const sem2Advice = 'https://docs.google.com/document/d/1ziFVqP3xdZhxYy9A19r_Vh05hR0kDqL2SclzSyeVPnY/edit?usp=drivesdk';

export const year2Subjects: Subject[] = [
  {
    id: 'engineering-mathematics-2', code: 'KIX1002', name: 'Engineering Mathematics 2', icon: '∫', color: 'lavender', description: 'Lecture notes, worked practice, revision files, and past papers for Semester 2 mathematics.', folderUrl: 'https://drive.google.com/drive/folders/1CbA75nzevaenrOaYvJZGWeC0WO9FZ3D0', advice: { summary: 'Engineering Mathematics 2 becomes manageable when you recognize the question type and practise the method repeatedly.', sourceUrl: sem2Advice, points: ['Read through the lecture notes to understand the scope, then group questions by method rather than studying them randomly.', 'Use tutorials and past papers to learn how each question type is solved. Redo the questions without looking at the solution.', 'Review the formula sheet regularly, especially before timed practice, and check the current scope with your lecturer.'] }, groups: [
      { label: 'Lecture notes', icon: '▤', description: 'Open the notes and weekly topic files.', links: [file('Week 1', 'Lecture note', '1E4_EVT6zgCzFkSni4PWYz-420bA0GAas'), file('Week 2', 'Lecture note', '1xl5qniL6tx-E1pGv_6NZ5YJyqyiB5n0-'), file('Week 3', 'Lecture note', '1bA8UXf12AJMP2DUq8aZN3M_L2Ti4y1Oc'), file('Week 4', 'Lecture note', '1YYVhhW1s4AuZwJNTHOX9XRWnHWt7eDCm'), file('Week 5', 'Lecture note', '1uah4d1dE3GuXQ7anya8C4iyMxrnGNHgU'), file('Week 6 · Power Series', 'Lecture note', '1KWNajCZ29uttCKZA_53Y2isoA6psGwJ_'), file('Week 7 · Frobenius Method', 'Lecture note', '1a-1abYFQUPK9YlDLbFrOpcv4-jHsWKxC'), file('Week 10 · Fourier Series 1', 'Lecture note', '1QFVsjEvrJF7RgtRj1HYQ-6fxo2DRw_vr'), file('Week 11 · Fourier Series 2', 'Lecture note', '10UWVBoBQwG-eQGVyaYNWK_wNRS6mE4Lh'), file('Week 12 · Partial Differential Equations', 'Lecture note', '1gh0ic43YMMe9vrL0JSfVzMCVr55XJY01'), file('Week 13 · Laplace + Wave', 'Lecture note', '1uhZtDD5n6x-1XAfJRjfzck1Upe62_-tN'), file('Week 14 · Heat Equation', 'Lecture note', '1rXy0tPR6ZJ6U0wGTLZ3aXJCJoQ7QuLlt')] },
      { label: 'Past year papers', icon: '▥', description: 'Past papers and exam preparation files.', links: [file('KIX1002 · 2025', 'Past year paper', '1JEMYkbMuusaYFzjaV_jZTYPS3KA6RQ2Y'), file('KIX1002 · 2023–24', 'Past year paper', '15hxgDKADK3GrP5MRTFPdwo5t_F8gcaWM'), file('KIX1002 · 2022–23', 'Past year paper', '17j8ajwXtYSm_0yc7ebJlnAlFaLx0EyTj'), file('Exam preparation', 'Revision paper', '1cx3-8jhu2Rsl8cyZgw3ppTE0MFkeNLzg')] },
      { label: 'Tutorial + solutions', icon: '✎', description: 'Tutorial practice files for the later topics.', links: [file('Tutorial 5', 'Tutorial practice', '1TxOD9wC5y9Vtm43xSx-rRZKTl2GsJ4SR'), file('Tutorial 10', 'Tutorial practice', '1QQmyyOllQHjAL-a824snRfefLEbE3tQJ'), file('Tutorial 12', 'Tutorial practice', '1umvewKYXuz0onPeaFQSioiICOsLHnEHg'), file('Tutorial 13', 'Tutorial practice', '1MXCXM-ojvRRJzay5nWSh8FltiHW90lLM'), folder('Tutorial folder', 'Full tutorial archive', '1GslT0dD2kxwgRsxNmlF65KW30rJ_mOlZ')] },
      { label: 'Additional materials', icon: '+', description: 'Open the complete Engineering Mathematics 2 Drive.', links: [folder('Whole subject Drive', 'All source materials', '1CbA75nzevaenrOaYvJZGWeC0WO9FZ3D0'), file('Cheat sheet', 'Quick revision', '1NuLqIhKyWuZotVxK4tCiaPHjzgrHsE-0')] },
    ]
  },
  {
    id: 'signal-system', code: 'KIE2006', name: 'Signals and Systems', icon: '≈', color: 'blue', description: 'Signals, LTI systems, Fourier analysis, sampling, and transform revision materials.', folderUrl: 'https://drive.google.com/drive/folders/1-V5ZiEr2C_z8V1cjLpGfDt-LRI6hWxOT', advice: { summary: 'Signals and Systems takes time at the beginning. Focus on worked examples, then build confidence by repeating the same problem patterns.', sourceUrl: sem2Advice, points: ['Use AI or a senior’s explanation when LTI systems or transforms are unclear, but return to the examples and solve them yourself.', 'Learn the execution steps for each example type. If one concept is blocking you for too long, move on and come back after practising a nearby example.', 'Use the notes, tutorials, and past papers together so you can connect the idea, the calculation, and the exam format.'] }, groups: [
      { label: 'Lecture notes', icon: '▤', description: 'Open notes by topic and week.', links: [file('Week 1 · Introduction', 'Lecture note', '1KNu3ec34_CqIE3QXXD3Kd-tpromNO_gJ'), file('Week 2 · LTI Systems', 'Lecture note', '1MvQTeuo4-KyvOYxEqsBCT-EMjbmMcmrN'), file('Week 3 · LTI Systems', 'Lecture note', '1RRdwkWtzppAQN1Qrpg88rNzwu6u2bpV3'), file('Week 3 · Fourier Series', 'Lecture note', '1GnpL_9k6Gy60t71f0xou0KstfR7asBwZ'), file('Week 4 · Fourier Series', 'Lecture note', '1dBLoSkpjb9xYnFALsuulc0ddvMdxzawI'), file('Week 5 · Fourier Transform', 'Lecture note', '1IiWVXEG6qQBH-T9Hi_G8Jcmxb7mOw46G'), file('Week 6 · Fourier Transform', 'Lecture note', '1mya4R0d2ExmEWrTkn5ExqbIXEQl_WRUN'), file('Week 7 · Sampling and Quantization', 'Lecture note', '1FJ1YyPR9MqK8ghs79I2y8PVLLlZJsT1H'), file('Week 8 · DTFS', 'Lecture note', '1_Smw_hNB63GLnrNr4uJxel6FNVj3ATMm'), file('Week 9 · DTFS', 'Lecture note', '1hwK4nOJW2ejZdAnq-CxYol61npcAnfee'), file('Week 10 · DTFT', 'Lecture note', '11MBnjJ_GW76nTF8n5-8PX96irXc55XHL'), file('Week 11 · DFT', 'Lecture note', '1aNwpxwiBySthzRMuadwsQ5MG1u6xd4Zx'), file('Week 12 · Laplace Transform', 'Lecture note', '1VXfk6f5BKkoWNRQuYx4-L5FSVmG91e_L'), file('Week 13 · Laplace Transform', 'Lecture note', '1Cw0xB2bTB7OcVDfRPGjqn09_j4IQ4uH1'), file('ROC reference', 'Reference note', '1pfAbqyEHE1mmnnEtjNUMxYvenzVWLwgx')] },
      { label: 'Past year papers', icon: '▥', description: 'Recent exam papers for timed practice.', links: [file('Final 2024–25', 'Past year paper', '1_Mb9TBwSjCuuSvoY-ePNDZfcVh8k0vq2'), file('KIE2006 · 2023–24', 'Past year paper', '1UeUAn9t7B-KaUSw_NWd0Q0sJdyeUauWg'), file('KIE2006 · 2022–23', 'Past year paper', '1IJpqbtNlsT8msn9-zT65gKplbdOkUtI0')] },
      { label: 'Tutorial + solutions', icon: '✎', description: 'Tutorial files and the full tutorial folder.', links: [file('Tutorial Week 2', 'Tutorial practice', '1vSucfGJ29H0ncAoMIp9k_n21XT77eNWy'), file('Tutorial Week 3', 'Tutorial practice', '1A8TLByDAlUTNqfTY5cQX2uw8NQpau9hQ'), folder('Tutorial folder', 'Full tutorial archive', '1FPH5_uLpCz5XJHORHn69O3Cs3-hsuc4B')] },
      { label: 'Additional materials', icon: '+', description: 'Open the complete Signals and Systems Drive.', links: [folder('Whole subject Drive', 'All source materials', '1-V5ZiEr2C_z8V1cjLpGfDt-LRI6hWxOT')] },
    ]
  },
  {
    id: 'electronic-physics', code: 'KIE1006', name: 'Electronic Physics', icon: '◌', color: 'indigo', description: 'Semiconductor physics, energy bands, crystal structures, and final exam preparation.', folderUrl: 'https://drive.google.com/drive/folders/1_62UhB6MSzA_742i3nuP50uveKrGNjHW', advice: { summary: 'Understand the concepts first, then practise the formulas and keywords that are most likely to appear in the final exam.', sourceUrl: sem2Advice, points: ['Review every lecture topic and keep a running formula list, including constants that are not provided in the exam.', 'Do past-year questions to practise both calculation and theory answers. Memorize the exact keywords needed for definitions and explanations.', 'Get the latest scope or exam hints from your lecturer before spending your final revision hours on low-priority topics.'] }, groups: [
      { label: 'Lecture notes', icon: '▤', description: 'Open the lecture slides by topic and week.', links: [file('Lecture 1 · Introduction to Semiconductor', 'Lecture note', '1PnB-fZB0q3rWONsMbl039oysGhpqwx_r'), file('Lecture 2 · Crystal Structures', 'Lecture note', '1txKocgq-WDjY5JY6HtdZrEUbcWDZ7McP'), file('Lecture 3 · Energy Band and Atomic Bonding', 'Lecture note', '1yLOfdJXmZrEzhipxGJ4j0tiLfEtQC9n8'), file('Lecture 3 · Atomic Packing Factor', 'Lecture note', '190uLfS6PokAnoW_GTTkYzATi4Y1WbZng'), file('Lecture 4 · Energy Band Theory', 'Lecture note', '1bHv74tGXpzKz8hB-l3CFKnQU0B0pKhgn'), file('Lecture 5 · Statistical Mechanics and Fermi-Dirac', 'Lecture note', '1rrkxHpnJKCYKictsqFU-S95Rm6cCtOQJ'), file('Week 6', 'Lecture note', '1-sc621ghtQlglvoSsIalyYB14PqTvS7N'), file('Week 7', 'Lecture note', '1bSnP-hgpz1rDS3KLud-Xl4njTGuPj4Xb'), file('Week 7 · Part II', 'Lecture note', '1jOJrsj0ZEYJWPgg4KKnyL-k86sDNtzrv'), file('Week 8', 'Lecture note', '1zTU4FmdzmFisgzRokX9UxyyXY-dscyaX'), file('Week 9', 'Lecture note', '1bOawM0vr4QZO028Z9XnOea3F7Oeys0m7'), file('Week 9 · Main', 'Lecture note', '1xT0k9BU--7i48sV1nOpF2DnoKUnSDbvs')] },
      { label: 'Past year papers', icon: '▥', description: 'Final examination papers for practice.', links: [file('Final 2023–24', 'Past year paper', '1Y93gCnCTIm6TjV5Ji5ryKMhgnzK5vAny'), file('Final 2022–23', 'Past year paper', '1kcmCMtJZDl7JMn1aQIhLNTYdufl4j-j6')] },
      { label: 'Tutorial + solutions', icon: '✎', description: 'Open the full tutorial folder.', links: [folder('Tutorial folder', 'Full tutorial archive', '1NyGHeuex0HreW8UCoi3DeWqY76fGTYWc'), folder('Past year paper folder', 'Extra practice archive', '1UWsUd1IS9bPBD2CLvt1vXJKUxfIIOFZS')] },
      { label: 'Additional materials', icon: '+', description: 'Open the complete Electronic Physics Drive.', links: [folder('Whole subject Drive', 'All source materials', '1_62UhB6MSzA_742i3nuP50uveKrGNjHW')] },
    ]
  },
  {
    id: 'electronic-circuit-1', code: 'KIE1007', name: 'Electronic Circuit 1', icon: '⌁', color: 'purple', description: 'Diodes, rectifiers, MOSFETs, op-amps, BJTs, and exam-focused circuit practice.', folderUrl: 'https://drive.google.com/drive/folders/1tpO45JfaGE2DNjo3ncnx9FuSyOrTX7s_', advice: { summary: 'Treat Electronic Circuit 1 as a calculation course: learn how each circuit works and practise finding voltages, currents, and resistances.', sourceUrl: sem2Advice, points: ['Prioritize diode and rectifier circuits, MOSFETs, op-amps, and BJTs. Understand how to identify nodes and choose the right model.', 'Refresh Ohm’s law, KCL, and KVL from Semester 1, then master both DC and small-signal AC analysis for MOSFETs and BJTs.', 'Memorize the equations and small-signal models because a formula sheet may not be provided. Op-amp analysis is a good early confidence builder.', 'Use the worked examples and tutorials to compare BJT and MOSFET assumptions. Always check signs, operating regions, and units.'] }, groups: [
      { label: 'Lecture notes', icon: '▤', description: 'Open the lecture notes by topic.', links: [file('Week 0', 'Lecture note', '1kV0uP66pSmIYGj8zX6t-xGpuIThisRbG'), file('Week 1', 'Lecture note', '1o4yuLvmBnUis46I9Wnwxv66loC9vDrXS'), file('Week 2', 'Lecture note', '1mYH1np78Qs-jJ_0BHWJQ7uKJDaqEuKYg'), file('Week 3', 'Lecture note', '17_wdvhAuksfU2GkgLDj5suz5KtgVr7FW'), file('Week 6', 'Lecture note', '1xP6I9TsOs3_o2ezMQ1H70sLj2AWbn68B'), file('Week 7', 'Lecture note', '1Fk1MhorHJ6MgMQ1BnkMDr0ADmTqcpaZI'), file('Week 7 · Alternate', 'Lecture note', '17yZ0N1Vn9tfrxH8lwE8ERnHZ3wWMyV7V'), file('Week 8 · MOSFET', 'Lecture note', '1x7wxtSCjwaL0ZIuFdmeWUtjgQZbwb0DQ'), file('MOSFET DC Analysis', 'Lecture note', '1Os9pe14iODG8iFR_oMTQ73tVxAUhw1tG'), file('MOSFET AC Analysis', 'Lecture note', '1Vkfzo3L48mTtn6ZAaGqb9IRrzpGmqr7y'), file('Introduction to Op-Amp', 'Lecture note', '1sKb35U76NwGsN_iUbqdQwM8toV9Y4don'), file('Op-Amp Analysis 1', 'Lecture note', '1fsQVlj7bHO37Ad6KtUFev0a5FCkJvghA'), file('Op-Amp Analysis 2', 'Lecture note', '11HX2riebwt-oiNWBXy6Y8mWMxW3P6RPV')] },
      { label: 'Past year papers', icon: '▥', description: 'Recent papers and revision exercises.', links: [file('KIE1007 · 2023–24', 'Past year paper', '1UbSb7YMNJseIpjJNHamdB2ueWqUSMJs8'), file('KIE1007 · 2024–25', 'Past year paper', '1WYkjFTNtt639mkkAh_1EPgC8a13QjA90'), file('KIE1007 · 2022', 'Past year paper', '1j7a3fvUUEYeVovv_zC9mCfHik1b-Z66W')] },
      { label: 'Tutorial + solutions', icon: '✎', description: 'Practice sets for diode, BJT, MOSFET, and op-amp analysis.', links: [file('Diode Exercise I', 'Tutorial practice', '1kXj09t0Ux3gD4PwoFKzV-6WCDmsL48ad'), file('Diode Exercise II', 'Tutorial practice', '1jz0Yf7oK-xDXsPUrhE2gG4TM42hzNhXK'), file('Tutorial 3 · BJT DC Analysis', 'Tutorial practice', '15HbuZKo80VCG1I3c-AolXOkAaYhkONzP'), file('Tutorial 4 · BJT AC Analysis', 'Tutorial practice', '1CndXbYNTrNwaSm5PdNhFuHDm6uRqFQZJ'), file('Tutorial 7 · Op-Amp', 'Tutorial practice', '1GJwfRCgeX9xoDCrQrKmuQRTNuH18ozeU'), file('MOSFET DC Exercise', 'Tutorial practice', '1_mIwMKD_pNabtTsxUiokTl2evNKOl2F9'), file('MOSFET AC Analysis', 'Tutorial practice', '15QhOPuNuVbyztwToAiOy_Hlkv7HyDUi6'), folder('Tutorial folder', 'Full tutorial archive', '1lCvfnCkm78yUIekRe7Zv5Lne9yUPMaCP')] },
      { label: 'Additional materials', icon: '+', description: 'Open the complete Electronic Circuit 1 Drive.', links: [folder('Whole subject Drive', 'All source materials', '1tpO45JfaGE2DNjo3ncnx9FuSyOrTX7s_'), file('Electronic Circuit Exam Use', 'Revision reference', '1CaeevJSTtjxZEAGJmFstapJ3l07K1UWW'), file('BJT Notes', 'Revision reference', '1_MXfJiG46ISaLFnJgBrDU51FvBKLSI5e')] },
    ]
  },
  {
    id: 'lab-1', code: 'KIE1001', name: 'Lab 1', icon: '⌁', color: 'lavender', description: 'Experiment reports, project examples, measurement files, and practical lab references.', folderUrl: 'https://drive.google.com/drive/folders/12xu0sj-QD4HxEDgrhkuDpLjuE8FDkXHB', advice: { summary: 'Keep your lab work organized from the first experiment: understand the setup, record measurements clearly, and use previous reports as structure references.', sourceUrl: sem2Advice, points: ['Read the experiment instructions before the lab and identify the circuit, measurements, and calculations you will need to complete.', 'Use previous reports to understand the expected structure, but write your own explanation, observations, and results.', 'Keep raw data, screenshots, calculations, and final graphs together so report writing is faster and easier.'] }, groups: [
      { label: 'Lab notes and experiments', icon: '▤', description: 'Experiment folders and project examples.', links: [folder('Mini Project', 'Project example archive', '1gtd5xAK4a9fCBWk-P-xaOhTXoUfwUUVJ'), folder('E21 and E11', 'Lab report and data files', '1-T7yB80w5hztixgTjvKIFQPD8a5u-kJK'), folder('E7 and E8', 'Lab report and data files', '1oqJpri0ciHlz1upROoGGB4x9Y6uqzTX2'), folder('D10 and D11', 'Lab report and photos', '1Pxf2In5iZzWK2PyV2-66eTwrt3SOdSma')] },
      { label: 'Past reports and examples', icon: '▥', description: 'Previous lab reports and practical references.', links: [file('E21 and E11 report · B8', 'Example report', '1YKRg_YRCw5Bx3T_xUYtrPOToCTo4tiGf'), file('E21 and E11 report · C6', 'Example report', '11iO5WfjooxR_3q4oKFxz1UTNLqLKn7Rj'), file('E7 and E8 report · B8', 'Example report', '1-wr66zo__xHL1waGi9JPG-J47p6b5XZ4'), file('E7 and E8 report · C6', 'Example report', '11g3lFjdimK5Jw97AVD59JZxtEnlLjZL2'), file('D10 and D11 report · B8', 'Example report', '1oSijjNUvNhhj-iAPKXFJShKle27_oElF')] },
      { label: 'Tutorial + solutions', icon: '✎', description: 'Measurement data and practical files.', links: [file('RLC 100 ohm data', 'Measurement archive', '1tMTSKdm_VqRc2bHQoH8KyELMNPPUPrkh'), file('RL 10k ohm data', 'Measurement archive', '14gqde8p7EiVLaQR1EKdQSjcd-XfUAVk9'), file('RLC 1k data', 'Measurement archive', '190QQPMmDoc7qhmyIfSFVzTCn5eNsEnpG'), file('RC 1k ohm data', 'Measurement archive', '1V9J5umHvJOli-Qz1SipN--ddz9ftGjmD'), file('RC 10k ohm data', 'Measurement archive', '1q7LUUqKpo5Ias_yAV9zYDRha_nLglrMY')] },
      { label: 'Additional materials', icon: '+', description: 'Open the complete Lab 1 Drive.', links: [folder('Whole subject Drive', 'All lab materials', '12xu0sj-QD4HxEDgrhkuDpLjuE8FDkXHB')] },
    ]
  },
];
