import { Arrow, SiteFooter, SiteHeader } from './components/SiteChrome';
import Reveal from './components/Reveal';
import { subjects } from './data';

const paths = [
  { href: '/resources', number: '01', title: 'Resource library', text: 'Open lecture notes by week, past-year papers, tutorials, solutions, and full subject folders.', icon: '▤' },
  { href: '/study-hub', number: '02', title: 'Study hub', text: 'Keep a Pomodoro session, daily target, checklist percentage, countdown, and reminders in one calm space.', icon: '◷' },
  { href: '/ai-library', number: '03', title: 'AI library', text: 'Copy exam-focused prompts with real examples for turning your own slides into useful revision.', icon: '✦' },
];

export default function Home() {
  return (
    <main>
      <SiteHeader />
      <Reveal className="home-hero-reveal"><section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> UM electrical engineering</div><h1>Your engineering<br /><span>starting point.</span></h1><p className="hero-text">EEz is a free, student-made study portal for UM electrical engineering students. Find the file, choose your next task, and keep moving.</p><div className="hero-actions"><a className="button button-dark" href="/resources">Browse resources <Arrow /></a><a className="text-link" href="/study-hub">Open study hub <Arrow /></a></div><div className="hero-proof"><div className="proof-avatars" aria-hidden="true"><span>∿</span><span>∫</span><span>01</span><span>✦</span></div><p><strong>Semester 1 and Semester 2</strong><br />organized for UM students</p></div></div><div className="hero-art" aria-label="A visual map of the EEz study portal"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-card hero-card-main"><div className="card-kicker">Your study library</div><div className="hero-card-title">Start where<br /><span>you are.</span></div><div className="mini-progress"><span /><span /><span /><span /><span /></div><div className="hero-card-footer"><span>Semester 1 + Semester 2</span><span>Free access ↗</span></div></div><div className="floating-note note-one"><span className="note-icon note-blue">∿</span><span><b>Lecture notes</b><small>open by week</small></span></div><div className="floating-note note-two"><span className="note-icon note-orange">✎</span><span><b>Study tools</b><small>focus · plan · revise</small></span></div><div className="hero-stamp">FREE<br /><small>FOR STUDENTS</small></div></div></section></Reveal>
      <Reveal className="home-stats-reveal" delay={0.06}><section className="stats-band"><div className="container stats-grid"><div><strong>04</strong><span>core courses</span></div><div><strong>03</strong><span>portal spaces</span></div><div><strong>∞</strong><span>free access</span></div><p>Less searching.<br /><b>More studying.</b></p></div></section></Reveal>
      <Reveal className="home-semester-reveal" delay={0.08}><section className="portal-section container"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> Choose your semester</div><h2>Start with the<br /><span>right semester.</span></h2></div><p>Select a resource library first, then open the exact subject and file you need.</p></div><div className="year-choices"><a className="year-card" href="/resources/year-1"><span className="year-number">01</span><span className="year-card-icon">∿</span><h3>Semester 1</h3><p>Four core courses</p><span className="path-link">Open Semester 1 library <Arrow /></span></a><a className="year-card" href="/resources/year-2"><span className="year-number">02</span><span className="year-card-icon">⚡︎</span><h3>Semester 2</h3><p>Five subjects including Lab 1</p><span className="path-link">Open Semester 2 library <Arrow /></span></a></div><div className="portal-subheading"><div className="eyebrow"><span className="eyebrow-line" /> The EEz portal</div><p>Resources, study tools, and AI prompts live on separate pages so you can get where you need to go quickly.</p></div><div className="path-grid">{paths.map((path, index) => <Reveal className="home-path-reveal" delay={0.04 + (index * 0.05)} key={path.href}><a className="path-card" href={path.href} key={path.href}><div className="path-card-top"><span className="path-number">{path.number}</span><span className="path-icon">{path.icon}</span></div><h3>{path.title}</h3><p>{path.text}</p><span className="path-link">Open page <Arrow /></span></a></Reveal>)}</div></section></Reveal>
      <Reveal className="home-course-reveal" delay={0.1}><section className="course-preview"><div className="container"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> Semester 1 preview</div><h2>Four courses.<br /><span>One home.</span></h2></div><p>Jump directly to a Semester 1 course, or use the semester selector above to open Semester 2.</p></div><div className="course-strip">{subjects.map((subject, index) => <Reveal className="home-course-chip-reveal" delay={0.04 + (index * 0.04)} key={subject.id}><a className="course-chip" href={'/resources/year-1#' + subject.id} key={subject.id}><span className="subject-icon">{subject.icon}</span><span><small>{subject.code}</small><b>{subject.name}</b></span><Arrow /></a></Reveal>)}</div><div className="course-cta"><span>Direct links to lecture notes by week, plus papers and tutorials.</span><a className="button button-light" href="/resources/year-1">See all Semester 1 resources <Arrow /></a></div></div></section></Reveal>
      <Reveal className="home-callout-reveal" delay={0.12}><section className="prompt-callout container"><div><div className="eyebrow"><span className="eyebrow-line" /> Built for exam season</div><h2>Make difficult topics<br /><span>easier to understand.</span></h2><p>Use the study hub for consistency and the AI library when a slide, chapter, or worked example needs a clearer explanation.</p></div><a className="button button-dark" href="/ai-library">Open AI library <Arrow /></a></section></Reveal>
      <SiteFooter />
    </main>
  );
}
